import {
  cell,
  statusCell,
  type ChinaAdminTableData,
} from "./china-admin-table-primitives"

export const settlementTables: Record<string, ChinaAdminTableData> = {
  merchantPendingSettlement: {
    filters: ["所属市场", "结算周期", "商户类型", "结算状态"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "market", labelKey: "chinaAdmin.tables.columns.market" },
      { key: "merchant", labelKey: "chinaAdmin.tables.columns.merchant" },
      { key: "settlementPeriod", labelKey: "chinaAdmin.tables.columns.settlementPeriod" },
      { key: "commissionRate", labelKey: "chinaAdmin.tables.columns.commissionRate" },
      { key: "settlementBoundary", labelKey: "chinaAdmin.tables.columns.settlementBoundary" },
      { key: "amount", labelKey: "chinaAdmin.tables.columns.amount" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "SET-20260503009",
        cells: {
          id: cell("SET-20260503009"),
          name: cell("三门海鲜市场 A12 档口待结算"),
          status: statusCell("chinaAdmin.status.settlement.pending", "orange"),
          market: cell("三门海鲜市场"),
          merchant: cell("A12 阿强鲜活海鲜"),
          settlementPeriod: cell("2026-05-01 至 2026-05-03"),
          commissionRate: cell("平台默认费率占位"),
          settlementBoundary: cell("只读 mock，不发起真实打款"),
          amount: cell("¥26,580.00"),
          updatedAt: cell("2026-05-03 09:00"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "SET-20260503016",
        cells: {
          id: cell("SET-20260503016"),
          name: cell("物料供应商 B 端订单待结算"),
          status: statusCell("chinaAdmin.status.settlement.pending", "orange"),
          market: cell("城北果蔬批发中心"),
          merchant: cell("市场物料供应商"),
          settlementPeriod: cell("2026-05-02 至 2026-05-03"),
          commissionRate: cell("商户采购链路费率占位"),
          settlementBoundary: cell("商户物料采购结算需独立规则，不混入消费者订单"),
          amount: cell("¥4,860.00"),
          updatedAt: cell("2026-05-03 18:20"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  settledRecords: {
    filters: ["所属市场", "结算完成时间", "商户类型", "金额区间"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "market", labelKey: "chinaAdmin.tables.columns.market" },
      { key: "merchant", labelKey: "chinaAdmin.tables.columns.merchant" },
      { key: "settlementPeriod", labelKey: "chinaAdmin.tables.columns.settlementPeriod" },
      { key: "settlementBoundary", labelKey: "chinaAdmin.tables.columns.settlementBoundary" },
      { key: "amount", labelKey: "chinaAdmin.tables.columns.amount" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "SET-20260502006",
        cells: {
          id: cell("SET-20260502006"),
          name: cell("城北果蔬 B08 档口结算批次"),
          status: statusCell("chinaAdmin.status.settlement.settled", "green"),
          market: cell("城北果蔬批发中心"),
          merchant: cell("B08 本地蔬果直供"),
          settlementPeriod: cell("2026-04-28 至 2026-05-02"),
          settlementBoundary: cell("已结算状态为 mock 展示，不代表真实打款完成"),
          amount: cell("¥18,240.00"),
          updatedAt: cell("2026-05-02 18:20"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  commissionRules: {
    filters: ["适用市场", "商户类型", "规则状态", "更新时间"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "market", labelKey: "chinaAdmin.tables.columns.market" },
      { key: "merchantType", labelKey: "chinaAdmin.tables.columns.merchantType" },
      { key: "commissionRate", labelKey: "chinaAdmin.tables.columns.commissionRate" },
      { key: "settlementBoundary", labelKey: "chinaAdmin.tables.columns.settlementBoundary" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "COMM-FRESH-DEFAULT",
        cells: {
          id: cell("COMM-FRESH-DEFAULT"),
          name: cell("本地鲜货默认佣金规则"),
          status: statusCell("chinaAdmin.status.settlement.mockOnly", "grey"),
          market: cell("平台默认 / 可按市场覆盖"),
          merchantType: cell("海鲜档口 / 水果蔬菜商户"),
          commissionRate: cell("占位：按品类与市场配置"),
          settlementBoundary: cell("只读规则草案，不参与真实佣金计算"),
          updatedAt: cell("2026-05-03 09:30"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "COMM-SUPPLIER-MATERIAL",
        cells: {
          id: cell("COMM-SUPPLIER-MATERIAL"),
          name: cell("物料供应商佣金规则占位"),
          status: statusCell("chinaAdmin.status.settlement.mockOnly", "grey"),
          market: cell("市场物料采购"),
          merchantType: cell("物料供应商"),
          commissionRate: cell("B 端采购链路单独配置"),
          settlementBoundary: cell("不混入消费者鲜货订单结算"),
          updatedAt: cell("2026-05-03 09:40"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  withdrawalRequests: {
    filters: ["提现状态", "提现方式", "所属市场", "负责人"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "merchant", labelKey: "chinaAdmin.tables.columns.merchant" },
      { key: "withdrawalMethod", labelKey: "chinaAdmin.tables.columns.withdrawalMethod" },
      { key: "safeBoundary", labelKey: "chinaAdmin.tables.columns.safeBoundary" },
      { key: "amount", labelKey: "chinaAdmin.tables.columns.amount" },
      { key: "owner", labelKey: "chinaAdmin.tables.columns.owner" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "WDR-20260503002",
        cells: {
          id: cell("WDR-20260503002"),
          name: cell("A12 档口提现申请占位"),
          status: statusCell("chinaAdmin.status.settlement.withdrawing", "blue"),
          merchant: cell("A12 阿强鲜活海鲜"),
          withdrawalMethod: cell("银行卡 / 对公账户占位"),
          safeBoundary: cell("只读 mock，不调用打款、不写真实账户"),
          amount: cell("¥12,000.00"),
          owner: cell("财务结算组"),
          updatedAt: cell("2026-05-03 15:20"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "WDR-20260502009",
        cells: {
          id: cell("WDR-20260502009"),
          name: cell("提现资料异常占位"),
          status: statusCell("chinaAdmin.status.settlement.exception", "red"),
          merchant: cell("B08 本地蔬果直供"),
          withdrawalMethod: cell("银行卡信息待核验"),
          safeBoundary: cell("需人工核验，不自动打款或改结算状态"),
          amount: cell("¥6,800.00"),
          owner: cell("财务风控组"),
          updatedAt: cell("2026-05-02 17:05"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
}
