import {
  cell,
  genericColumns,
  statusCell,
  type ChinaAdminStatusColor,
  type ChinaAdminTableData,
  type ChinaAdminTableRow,
} from "./china-admin-table-primitives"

const pickupRow = (
  id: string,
  name: string,
  statusKey: string,
  statusColor: ChinaAdminStatusColor,
  owner: string,
  amount: string,
  updatedAt: string,
  actions: string[] = ["view", "remark"],
): ChinaAdminTableRow => ({
  id,
  cells: {
    id: cell(id),
    name: cell(name),
    status: statusCell(statusKey, statusColor),
    owner: cell(owner),
    amount: cell(amount),
    updatedAt: cell(updatedAt),
  },
  actions,
})

export const pickupCardTables: Record<string, ChinaAdminTableData> = {
  pickupCardTypes: {
    columns: genericColumns,
    filters: ["卡种状态", "适用商品", "有效期", "更新时间"],
    primaryActionKey: "chinaAdmin.actions.createPickupCardPlaceholder",
    rows: [
      pickupRow(
        "PCT-SEAFOOD-GIFT-001",
        "端午鲜果礼盒提货卡",
        "chinaAdmin.status.pickupCard.activated",
        "green",
        "提货卡运营组",
        "可兑换指定商品或套餐，不是优惠券、储值卡或支付方式",
        "2026-05-03 09:00",
      ),
      pickupRow(
        "PCT-SEAFOOD-LIVE-002",
        "鲜活海鲜套餐提货卡",
        "chinaAdmin.status.pickupCard.pendingActivation",
        "orange",
        "提货卡运营组",
        "待运营确认可兑换商品和配送窗口",
        "2026-05-03 09:08",
      ),
    ],
  },
  pickupCardBatches: {
    columns: genericColumns,
    filters: ["批次状态", "渠道", "制卡数量", "更新时间"],
    primaryActionKey: "chinaAdmin.actions.createPickupCardPlaceholder",
    rows: [
      pickupRow(
        "BATCH-202605-A01",
        "华东商超渠道 5 月批次",
        "chinaAdmin.status.pickupBatch.produced",
        "blue",
        "渠道运营组",
        "20,000 张，未展示真实卡密",
        "2026-05-03 09:16",
      ),
      pickupRow(
        "BATCH-202605-A02",
        "市场线下团购渠道批次",
        "chinaAdmin.status.pickupBatch.pendingActivation",
        "orange",
        "渠道运营组",
        "8,000 张，待激活",
        "2026-05-03 09:20",
      ),
    ],
  },
  pickupCardNumbers: {
    columns: genericColumns,
    filters: ["卡号状态", "脱敏卡号", "绑定状态", "更新时间"],
    rows: [
      pickupRow(
        "THK-2026-0001-7831",
        "THK-2026-****-7831",
        "chinaAdmin.status.pickupCard.bound",
        "blue",
        "提货卡客服组",
        "卡密永不明文展示，仅显示脱敏卡号",
        "2026-05-03 09:28",
      ),
      pickupRow(
        "THK-2026-0001-9288",
        "THK-2026-****-9288",
        "chinaAdmin.status.pickupCard.activated",
        "green",
        "提货卡运营组",
        "已激活，未提货",
        "2026-05-03 09:32",
      ),
    ],
  },
  pickupCardRedemptions: {
    columns: genericColumns,
    filters: ["提货状态", "配送方式", "手机号", "更新时间"],
    rows: [
      pickupRow(
        "RDO-202605030018",
        "用户已提交提货信息",
        "chinaAdmin.status.pickupCard.redeemed",
        "green",
        "提货履约组",
        "线上填写收货地址后履约，不进入购物车支付",
        "2026-05-03 10:45",
      ),
      pickupRow(
        "RDO-202605030021",
        "用户待补充配送日期",
        "chinaAdmin.status.pickupCard.partiallyRedeemed",
        "orange",
        "提货客服组",
        "待用户确认配送窗口",
        "2026-05-03 10:22",
      ),
    ],
  },
  pickupCardFreezeVoid: {
    columns: genericColumns,
    filters: ["风控状态", "操作类型", "渠道", "更新时间"],
    rows: [
      pickupRow(
        "THK-FREEZE-20260503001",
        "高频查询风险占位",
        "chinaAdmin.status.pickupCard.frozen",
        "red",
        "提货卡风控组",
        "只读占位，不冻结真实卡号",
        "2026-05-03 10:08",
        ["view", "review", "remark"],
      ),
      pickupRow(
        "THK-VOID-20260503002",
        "渠道作废申请占位",
        "chinaAdmin.status.pickupCard.voided",
        "grey",
        "渠道运营组",
        "不执行真实作废",
        "2026-05-03 09:58",
      ),
    ],
  },
  pickupCardOperationLogs: {
    columns: genericColumns,
    filters: ["操作类型", "操作人", "卡号", "更新时间"],
    rows: [
      pickupRow(
        "PLOG-20260503001",
        "查看脱敏卡号详情",
        "chinaAdmin.status.settings.placeholder",
        "grey",
        "平台管理员",
        "审计日志占位，不写真实审计服务",
        "2026-05-03 11:12",
      ),
      pickupRow(
        "PLOG-20260503002",
        "备注提货异常线索",
        "chinaAdmin.status.settings.placeholder",
        "grey",
        "提货卡客服组",
        "备注占位，不改变卡状态",
        "2026-05-03 10:58",
      ),
    ],
  },
  pickupCardChannels: {
    columns: genericColumns,
    filters: ["渠道状态", "渠道类型", "批次数", "更新时间"],
    rows: [
      pickupRow(
        "PCH-202605-SUPER",
        "华东商超渠道",
        "chinaAdmin.status.settings.active",
        "green",
        "渠道运营组",
        "线下实体卡销售渠道，不做渠道结算",
        "2026-05-03 09:46",
      ),
      pickupRow(
        "PCH-202605-GROUP",
        "企业团购渠道",
        "chinaAdmin.status.settings.placeholder",
        "grey",
        "渠道运营组",
        "批量发卡占位，不展示真实卡密",
        "2026-05-03 09:40",
      ),
    ],
  },
  pickupCardOrders: {
    columns: genericColumns,
    filters: ["提货订单状态", "履约方式", "所属市场", "更新时间"],
    rows: [
      pickupRow(
        "PKO-202605030001",
        "鲜果礼盒提货履约单",
        "chinaAdmin.status.pickupOrder.pendingShipment",
        "orange",
        "提货履约组",
        "由提货生成履约占位，不创建真实订单、不扣库存",
        "2026-05-03 10:38",
      ),
      pickupRow(
        "PKO-202605030002",
        "海鲜套餐预约配送单",
        "chinaAdmin.status.pickupOrder.pendingConfirm",
        "blue",
        "提货客服组",
        "待确认配送窗口",
        "2026-05-03 10:12",
      ),
    ],
  },
}
