import { riskColumns } from "./china-admin-table-columns"
import {
  cell,
  statusCell,
  type ChinaAdminTableData,
} from "./china-admin-table-primitives"

const riskFilters = ["风险等级", "风险对象", "所属市场", "负责人"]

export const riskTables: Record<string, ChinaAdminTableData> = {
  riskDashboard: {
    columns: riskColumns,
    filters: riskFilters,
    rows: [
      {
        id: "RISK-DASH-20260503001",
        cells: {
          id: cell("RISK-DASH-20260503001"),
          name: cell("今日平台风控队列"),
          status: statusCell("chinaAdmin.status.risk.processing", "blue"),
          riskObject: cell("商户 / 商品 / 订单 / 提货卡"),
          riskType: cell("运营预警汇总"),
          riskLevel: cell("中风险"),
          triggerRule: cell("mock 汇总规则，不接真实规则引擎"),
          riskBoundary: cell("只读看板，不处罚、不退款、不冻结、不改权限"),
          owner: cell("风控运营组"),
          updatedAt: cell("2026-05-03 10:30"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "RISK-DASH-20260503002",
        cells: {
          id: cell("RISK-DASH-20260503002"),
          name: cell("提货卡异常尝试提醒"),
          status: statusCell("chinaAdmin.status.risk.pending", "orange"),
          riskObject: cell("提货卡 THK-2026-****-7831"),
          riskType: cell("短时高频查询"),
          riskLevel: cell("中风险"),
          triggerRule: cell("同手机号多次查询 / 提货尝试"),
          riskBoundary: cell("只读预警，不冻结真实卡号或拒绝提货"),
          owner: cell("提货卡风控组"),
          updatedAt: cell("2026-05-03 10:26"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  merchantRisk: {
    columns: riskColumns,
    filters: ["风险等级", "商户类型", "所属市场", "负责人"],
    rows: [
      {
        id: "RISK-M-20260503006",
        cells: {
          id: cell("RISK-M-20260503006"),
          name: cell("商户证照即将到期"),
          status: statusCell("chinaAdmin.status.risk.pending", "orange"),
          riskObject: cell("A12 阿强鲜活海鲜"),
          riskType: cell("资质有效期提醒"),
          riskLevel: cell("低风险"),
          triggerRule: cell("营业执照有效期 mock 检查"),
          riskBoundary: cell("只读提醒，不停用商户、不改店铺状态"),
          owner: cell("商户运营组"),
          updatedAt: cell("2026-05-03 09:52"),
        },
        actions: ["view", "review", "remark"],
      },
      {
        id: "RISK-M-20260503007",
        cells: {
          id: cell("RISK-M-20260503007"),
          name: cell("物料供应商履约投诉增多"),
          status: statusCell("chinaAdmin.status.risk.processing", "blue"),
          riskObject: cell("M03 泡沫箱供应商"),
          riskType: cell("B 端履约风险"),
          riskLevel: cell("中风险"),
          triggerRule: cell("商户投诉记录 mock 汇总"),
          riskBoundary: cell("不处罚、不关闭接单能力，只做运营跟进占位"),
          owner: cell("商户运营组"),
          updatedAt: cell("2026-05-03 09:44"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  productRisk: {
    columns: riskColumns,
    filters: ["风险等级", "商品类目", "所属市场", "负责人"],
    rows: [
      {
        id: "RISK-P-20260503011",
        cells: {
          id: cell("RISK-P-20260503011"),
          name: cell("规格单位疑似缺失"),
          status: statusCell("chinaAdmin.status.risk.pending", "orange"),
          riskObject: cell("鲜活梭子蟹"),
          riskType: cell("规格模板完整性"),
          riskLevel: cell("低风险"),
          triggerRule: cell("商品标题有价格区间但规格字段为空"),
          riskBoundary: cell("只读质检提示，不下架、不改商品"),
          owner: cell("商品审核组"),
          updatedAt: cell("2026-05-03 10:18"),
        },
        actions: ["view", "review", "remark"],
      },
      {
        id: "RISK-P-20260503012",
        cells: {
          id: cell("RISK-P-20260503012"),
          name: cell("禁售词命中占位"),
          status: statusCell("chinaAdmin.status.risk.processing", "blue"),
          riskObject: cell("外地批发商供货商品"),
          riskType: cell("商品内容风控"),
          riskLevel: cell("中风险"),
          triggerRule: cell("mock 关键词命中，不接真实规则引擎"),
          riskBoundary: cell("不自动驳回、不自动下架"),
          owner: cell("商品审核组"),
          updatedAt: cell("2026-05-03 10:10"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  orderRisk: {
    columns: riskColumns,
    filters: ["风险等级", "订单状态", "支付状态", "负责人"],
    rows: [
      {
        id: "RISK-O-20260503021",
        cells: {
          id: cell("RISK-O-20260503021"),
          name: cell("同手机号多商户异常售后"),
          status: statusCell("chinaAdmin.status.risk.processing", "blue"),
          riskObject: cell("售后单 AS-20260503012"),
          riskType: cell("退款频次 / 金额异常"),
          riskLevel: cell("高风险"),
          triggerRule: cell("同手机号多商户短期售后 mock 汇总"),
          riskBoundary: cell("不触发真实退款拒绝或账户限制"),
          owner: cell("售后风控组"),
          updatedAt: cell("2026-05-03 10:02"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "RISK-O-20260503022",
        cells: {
          id: cell("RISK-O-20260503022"),
          name: cell("支付通知延迟占位"),
          status: statusCell("chinaAdmin.status.risk.pending", "orange"),
          riskObject: cell("PAY-20260503018"),
          riskType: cell("支付通知状态"),
          riskLevel: cell("中风险"),
          triggerRule: cell("异步通知超时 mock 检查"),
          riskBoundary: cell("只提示排查，不以前端返回页判定支付成功"),
          owner: cell("支付运营组"),
          updatedAt: cell("2026-05-03 09:56"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  pickupCardRisk: {
    columns: riskColumns,
    filters: ["风险等级", "卡状态", "渠道", "负责人"],
    rows: [
      {
        id: "RISK-C-20260503031",
        cells: {
          id: cell("RISK-C-20260503031"),
          name: cell("高频提货尝试占位预警"),
          status: statusCell("chinaAdmin.status.risk.pending", "orange"),
          riskObject: cell("提货卡 THK-2026-****-7831"),
          riskType: cell("提货频次异常"),
          riskLevel: cell("中风险"),
          triggerRule: cell("短时间多次查询 / 提货尝试"),
          riskBoundary: cell("只读预警，不冻结真实卡号"),
          owner: cell("提货卡风控组"),
          updatedAt: cell("2026-05-03 10:26"),
        },
        actions: ["view", "review", "remark"],
      },
      {
        id: "RISK-C-20260503032",
        cells: {
          id: cell("RISK-C-20260503032"),
          name: cell("渠道批次激活异常"),
          status: statusCell("chinaAdmin.status.risk.processing", "blue"),
          riskObject: cell("BATCH-202605-A01"),
          riskType: cell("渠道激活节奏异常"),
          riskLevel: cell("中风险"),
          triggerRule: cell("同渠道短时大量激活 mock 预警"),
          riskBoundary: cell("不作废、不冻结、不改真实批次状态"),
          owner: cell("渠道运营组"),
          updatedAt: cell("2026-05-03 10:08"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  riskOperationLogs: {
    columns: riskColumns,
    filters: ["操作类型", "风险对象", "负责人", "更新时间"],
    rows: [
      {
        id: "RLOG-20260503001",
        cells: {
          id: cell("RLOG-20260503001"),
          name: cell("查看商户风险详情"),
          status: statusCell("chinaAdmin.status.risk.closed", "grey"),
          riskObject: cell("A12 阿强鲜活海鲜"),
          riskType: cell("审计日志占位"),
          riskLevel: cell("低风险"),
          triggerRule: cell("运营查看记录 mock"),
          riskBoundary: cell("只读日志，不写真实审计服务"),
          owner: cell("平台管理员"),
          updatedAt: cell("2026-05-03 11:12"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "RLOG-20260503002",
        cells: {
          id: cell("RLOG-20260503002"),
          name: cell("备注提货卡风险线索"),
          status: statusCell("chinaAdmin.status.risk.closed", "grey"),
          riskObject: cell("THK-2026-****-7831"),
          riskType: cell("审计日志占位"),
          riskLevel: cell("低风险"),
          triggerRule: cell("运营备注 mock"),
          riskBoundary: cell("不保存真实操作日志、不改卡状态"),
          owner: cell("提货卡风控组"),
          updatedAt: cell("2026-05-03 10:58"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
}
