import {
  cell,
  statusCell,
  type ChinaAdminTableData,
} from "./china-admin-table-primitives"

const paymentSafetyColumns = [
  { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
  { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
  { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
  { key: "paymentMethod", labelKey: "chinaAdmin.tables.columns.paymentMethod" },
  { key: "providerEventId", labelKey: "chinaAdmin.tables.columns.providerEventId" },
  { key: "notificationState", labelKey: "chinaAdmin.tables.columns.notificationState" },
  { key: "idempotencyKey", labelKey: "chinaAdmin.tables.columns.idempotencyKey" },
  { key: "verifyState", labelKey: "chinaAdmin.tables.columns.verifyState" },
  { key: "amount", labelKey: "chinaAdmin.tables.columns.amount" },
  { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
  { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
]

export const paymentTables: Record<string, ChinaAdminTableData> = {
  paymentTransactions: {
    filters: ["支付方式", "通知状态", "对账状态", "更新时间"],
    columns: paymentSafetyColumns,
    rows: [
      {
        id: "PAY-20260503071",
        cells: {
          id: cell("PAY-20260503071"),
          name: cell("本地市场支付流水占位"),
          status: statusCell("chinaAdmin.status.payment.pendingReconcile", "orange"),
          paymentMethod: cell("Mock China PaymentProvider"),
          providerEventId: cell("mock_pay_evt_20260503071"),
          notificationState: cell("已接收异步通知，待对账"),
          idempotencyKey: cell("mock_event_PAY-20260503071"),
          verifyState: cell("mock 验签通过占位"),
          amount: cell("¥8,620.00"),
          updatedAt: cell("2026-05-03 08:30"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "PAY-20260502018",
        cells: {
          id: cell("PAY-20260502018"),
          name: cell("支付通知异常占位"),
          status: statusCell("chinaAdmin.status.payment.exception", "red"),
          paymentMethod: cell("Mock China PaymentProvider"),
          providerEventId: cell("mock_pay_evt_20260502018"),
          notificationState: cell("重复通知 / 金额差异待核查"),
          idempotencyKey: cell("mock_event_PAY-20260502018"),
          verifyState: cell("必须先验签再处理，不能重复改订单"),
          amount: cell("¥168.00"),
          updatedAt: cell("2026-05-02 16:36"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  refundTransactions: {
    filters: ["退款状态", "售后单号", "支付方式", "更新时间"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "paymentMethod", labelKey: "chinaAdmin.tables.columns.paymentMethod" },
      { key: "orderNo", labelKey: "chinaAdmin.tables.columns.orderNo" },
      { key: "providerEventId", labelKey: "chinaAdmin.tables.columns.providerEventId" },
      { key: "safeBoundary", labelKey: "chinaAdmin.tables.columns.safeBoundary" },
      { key: "amount", labelKey: "chinaAdmin.tables.columns.amount" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "REF-20260503018",
        cells: {
          id: cell("REF-20260503018"),
          name: cell("鲜活损耗退款流水占位"),
          status: statusCell("chinaAdmin.status.payment.mockOnly", "grey"),
          paymentMethod: cell("Mock China PaymentProvider"),
          orderNo: cell("O-202605030120 / AS-20260503012"),
          providerEventId: cell("mock_refund_evt_20260503018"),
          safeBoundary: cell("只读 mock，不触发真实退款"),
          amount: cell("¥68.00"),
          updatedAt: cell("2026-05-03 11:20"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  reconciliationStatements: {
    filters: ["账期", "所属市场", "对账状态", "更新时间"],
    columns: [
      { key: "statementNo", labelKey: "chinaAdmin.tables.columns.statementNo" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "billDate", labelKey: "chinaAdmin.tables.columns.billDate" },
      { key: "market", labelKey: "chinaAdmin.tables.columns.market" },
      { key: "reconcileState", labelKey: "chinaAdmin.tables.columns.reconcileState" },
      { key: "safeBoundary", labelKey: "chinaAdmin.tables.columns.safeBoundary" },
      { key: "amount", labelKey: "chinaAdmin.tables.columns.amount" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "REC-20260503-SM",
        cells: {
          statementNo: cell("REC-20260503-SM"),
          name: cell("三门海鲜市场日对账单"),
          status: statusCell("chinaAdmin.status.payment.pendingReconcile", "orange"),
          billDate: cell("2026-05-03"),
          market: cell("三门海鲜市场"),
          reconcileState: cell("平台流水与 mock provider 流水待核对"),
          safeBoundary: cell("只读展示，不改支付/订单/结算状态"),
          amount: cell("¥286,430.00"),
          updatedAt: cell("2026-05-03 23:30"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "REC-20260502-CB",
        cells: {
          statementNo: cell("REC-20260502-CB"),
          name: cell("城北果蔬批发中心日对账单"),
          status: statusCell("chinaAdmin.status.payment.reconciled", "green"),
          billDate: cell("2026-05-02"),
          market: cell("城北果蔬批发中心"),
          reconcileState: cell("mock 已对账"),
          safeBoundary: cell("仅为运营看板占位"),
          amount: cell("¥128,560.00"),
          updatedAt: cell("2026-05-02 23:20"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  abnormalBills: {
    filters: ["异常类型", "支付方式", "风险等级", "负责人"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "paymentMethod", labelKey: "chinaAdmin.tables.columns.paymentMethod" },
      { key: "providerEventId", labelKey: "chinaAdmin.tables.columns.providerEventId" },
      { key: "differenceReason", labelKey: "chinaAdmin.tables.columns.differenceReason" },
      { key: "safeBoundary", labelKey: "chinaAdmin.tables.columns.safeBoundary" },
      { key: "owner", labelKey: "chinaAdmin.tables.columns.owner" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "ABN-20260502018",
        cells: {
          id: cell("ABN-20260502018"),
          name: cell("金额差异异常账单"),
          status: statusCell("chinaAdmin.status.payment.exception", "red"),
          paymentMethod: cell("Mock China PaymentProvider"),
          providerEventId: cell("mock_pay_evt_20260502018"),
          differenceReason: cell("Provider 通知金额与平台订单金额不一致"),
          safeBoundary: cell("先验签、幂等记录、人工核查，不自动改订单"),
          owner: cell("财务对账组"),
          updatedAt: cell("2026-05-02 16:40"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
}
