import {
  cell,
  statusCell,
  type ChinaAdminTableData,
} from "./china-admin-table-primitives"

export const afterSalesTables: Record<string, ChinaAdminTableData> = {
  refundRequests: {
    filters: ["售后类型", "退款金额", "所属市场", "处理时长"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "afterSalesType", labelKey: "chinaAdmin.tables.columns.afterSalesType" },
      { key: "orderNo", labelKey: "chinaAdmin.tables.columns.orderNo" },
      { key: "buyer", labelKey: "chinaAdmin.tables.columns.buyer" },
      { key: "merchant", labelKey: "chinaAdmin.tables.columns.merchant" },
      { key: "refundBoundary", labelKey: "chinaAdmin.tables.columns.refundBoundary" },
      { key: "amount", labelKey: "chinaAdmin.tables.columns.amount" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "RF-20260503018",
        cells: {
          id: cell("RF-20260503018"),
          name: cell("鲜活梭子蟹损耗退款申请"),
          status: statusCell("chinaAdmin.status.afterSales.pending", "orange"),
          afterSalesType: cell("仅退款"),
          orderNo: cell("O-202605030120"),
          buyer: cell("138****8291"),
          merchant: cell("A12 阿强鲜活海鲜"),
          refundBoundary: cell("只读展示，不触发真实退款"),
          amount: cell("¥68.00"),
          updatedAt: cell("2026-05-03 11:12"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "RF-20260502044",
        cells: {
          id: cell("RF-20260502044"),
          name: cell("果蔬重量差异退款申请"),
          status: statusCell("chinaAdmin.status.afterSales.processing", "blue"),
          afterSalesType: cell("部分退款"),
          orderNo: cell("O-202605030144"),
          buyer: cell("159****6208"),
          merchant: cell("B08 本地蔬果直供"),
          refundBoundary: cell("等待售后专员核对凭证"),
          amount: cell("¥12.00"),
          updatedAt: cell("2026-05-02 17:26"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  returnRefunds: {
    filters: ["退货状态", "配送方式", "商品类型", "所属市场"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "afterSalesType", labelKey: "chinaAdmin.tables.columns.afterSalesType" },
      { key: "deliveryMode", labelKey: "chinaAdmin.tables.columns.deliveryMode" },
      { key: "evidence", labelKey: "chinaAdmin.tables.columns.evidence" },
      { key: "resolution", labelKey: "chinaAdmin.tables.columns.resolution" },
      { key: "owner", labelKey: "chinaAdmin.tables.columns.owner" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "RR-20260503007",
        cells: {
          id: cell("RR-20260503007"),
          name: cell("冻品包装破损退货退款"),
          status: statusCell("chinaAdmin.status.afterSales.pending", "orange"),
          afterSalesType: cell("退货退款"),
          deliveryMode: cell("市场统一配送"),
          evidence: cell("买家图片、配送签收备注"),
          resolution: cell("待确认责任方，不能自动退款"),
          owner: cell("售后运营组"),
          updatedAt: cell("2026-05-03 10:28"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  platformInterventions: {
    filters: ["介入原因", "风险等级", "所属市场", "负责人"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "market", labelKey: "chinaAdmin.tables.columns.market" },
      { key: "orderNo", labelKey: "chinaAdmin.tables.columns.orderNo" },
      { key: "evidence", labelKey: "chinaAdmin.tables.columns.evidence" },
      { key: "resolution", labelKey: "chinaAdmin.tables.columns.resolution" },
      { key: "owner", labelKey: "chinaAdmin.tables.columns.owner" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "PI-20260502031",
        cells: {
          id: cell("PI-20260502031"),
          name: cell("跨档口配送延迟投诉"),
          status: statusCell("chinaAdmin.status.afterSales.intervention", "red"),
          market: cell("三门海鲜市场 / 城北果蔬批发中心"),
          orderNo: cell("O-202605020771"),
          evidence: cell("配送轨迹占位、用户聊天占位、商家说明"),
          resolution: cell("平台人工介入，只读记录责任建议"),
          owner: cell("平台售后专员"),
          updatedAt: cell("2026-05-02 16:55"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  afterSalesReasons: {
    filters: ["适用范围", "责任方", "是否启用", "更新时间"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "reasonScope", labelKey: "chinaAdmin.tables.columns.reasonScope" },
      { key: "merchantType", labelKey: "chinaAdmin.tables.columns.merchantType" },
      { key: "resolution", labelKey: "chinaAdmin.tables.columns.resolution" },
      { key: "owner", labelKey: "chinaAdmin.tables.columns.owner" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "ASR-FRESH-LOSS",
        cells: {
          id: cell("ASR-FRESH-LOSS"),
          name: cell("鲜活到货损耗"),
          status: statusCell("chinaAdmin.status.afterSales.resolved", "green"),
          reasonScope: cell("消费者售后 / 鲜活海鲜"),
          merchantType: cell("海鲜档口"),
          resolution: cell("引导上传图片、签收时间、重量差异"),
          owner: cell("售后规则运营"),
          updatedAt: cell("2026-05-03 09:15"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "ASR-MATERIAL-NOT-CONSUMER",
        cells: {
          id: cell("ASR-MATERIAL-NOT-CONSUMER"),
          name: cell("市场物料售后"),
          status: statusCell("chinaAdmin.status.settings.placeholder", "grey"),
          reasonScope: cell("商户 B 端采购，不进入消费者售后首页"),
          merchantType: cell("物料供应商"),
          resolution: cell("后续在商户采购/供应商订单中单独处理"),
          owner: cell("平台运营组"),
          updatedAt: cell("2026-05-03 09:20"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
}
