import { orderColumns } from "./china-admin-table-columns"
import { orderRows } from "./china-admin-table-core-rows"
import {
  cell,
  statusCell,
  type ChinaAdminTableData,
} from "./china-admin-table-primitives"

export const orderTables: Record<string, ChinaAdminTableData> = {
  allOrders: {
    filters: ["订单状态", "所属市场", "配送方式", "支付状态", "更新时间"],
    columns: orderColumns,
    rows: orderRows,
  },
  pendingPaymentOrders: {
    filters: ["支付等待时长", "支付方式", "所属市场", "更新时间"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "market", labelKey: "chinaAdmin.tables.columns.market" },
      { key: "paymentMethod", labelKey: "chinaAdmin.tables.columns.paymentMethod" },
      { key: "paymentState", labelKey: "chinaAdmin.tables.columns.paymentState" },
      { key: "owner", labelKey: "chinaAdmin.tables.columns.owner" },
      { key: "amount", labelKey: "chinaAdmin.tables.columns.amount" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "O-202605030221",
        cells: {
          id: cell("O-202605030221"),
          name: cell("鲜活海鲜购物车订单"),
          status: statusCell("chinaAdmin.status.order.pendingPayment", "orange"),
          market: cell("三门海鲜市场"),
          paymentMethod: cell("Mock China PaymentProvider"),
          paymentState: cell("等待后端异步支付通知，不能以前端跳转为准"),
          owner: cell("A12 阿强鲜活海鲜"),
          amount: cell("¥412.00"),
          updatedAt: cell("2026-05-03 11:18"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  pendingShipmentOrders: {
    filters: ["备货时长", "配送方式", "所属市场", "档口"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "market", labelKey: "chinaAdmin.tables.columns.market" },
      { key: "deliveryMode", labelKey: "chinaAdmin.tables.columns.deliveryMode" },
      { key: "fulfillmentState", labelKey: "chinaAdmin.tables.columns.fulfillmentState" },
      { key: "deliveryWindow", labelKey: "chinaAdmin.tables.columns.deliveryWindow" },
      { key: "owner", labelKey: "chinaAdmin.tables.columns.owner" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "O-202605030120",
        cells: {
          id: cell("O-202605030120"),
          name: cell("海鲜拼单配送订单"),
          status: statusCell("chinaAdmin.status.order.pendingShipment", "orange"),
          market: cell("三门海鲜市场"),
          deliveryMode: cell("市场统一配送"),
          fulfillmentState: cell("待档口备货并交给配送调度"),
          deliveryWindow: cell("今日 15:00-17:00"),
          owner: cell("A12 阿强鲜活海鲜"),
          updatedAt: cell("2026-05-03 11:05"),
        },
        actions: ["view", "remark"],
      },
      {
        id: "O-202605030144",
        cells: {
          id: cell("O-202605030144"),
          name: cell("果蔬次日达订单"),
          status: statusCell("chinaAdmin.status.order.pendingShipment", "orange"),
          market: cell("城北果蔬批发中心"),
          deliveryMode: cell("商家自配"),
          fulfillmentState: cell("商家自行备货，平台只展示状态"),
          deliveryWindow: cell("明日 09:00-12:00"),
          owner: cell("B08 本地蔬果直供"),
          updatedAt: cell("2026-05-03 10:56"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  pendingReceiptOrders: {
    filters: ["配送方式", "收货区域", "所属市场", "更新时间"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "deliveryMode", labelKey: "chinaAdmin.tables.columns.deliveryMode" },
      { key: "receiverArea", labelKey: "chinaAdmin.tables.columns.receiverArea" },
      { key: "fulfillmentState", labelKey: "chinaAdmin.tables.columns.fulfillmentState" },
      { key: "owner", labelKey: "chinaAdmin.tables.columns.owner" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "O-202605030188",
        cells: {
          id: cell("O-202605030188"),
          name: cell("鲜活梭子蟹到店自提"),
          status: statusCell("chinaAdmin.status.order.pendingReceipt", "blue"),
          deliveryMode: cell("消费者到档口自提"),
          receiverArea: cell("三门海鲜市场 A 区"),
          fulfillmentState: cell("备货完成，待消费者取货"),
          owner: cell("A12 阿强鲜活海鲜"),
          updatedAt: cell("2026-05-03 10:42"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  completedOrders: {
    filters: ["完成时间", "所属市场", "配送方式", "金额区间"],
    columns: orderColumns,
    rows: [
      {
        id: "O-202605020516",
        cells: {
          id: cell("O-202605020516"),
          name: cell("今日鲜货组合订单"),
          status: statusCell("chinaAdmin.status.order.completed", "green"),
          market: cell("三门海鲜市场"),
          deliveryMode: cell("市场统一配送"),
          paymentState: cell("已支付"),
          fulfillmentState: cell("已签收"),
          owner: cell("A12 阿强鲜活海鲜"),
          amount: cell("¥286.00"),
          updatedAt: cell("2026-05-02 20:16"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  closedOrders: {
    filters: ["关闭原因", "支付状态", "所属市场", "更新时间"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "market", labelKey: "chinaAdmin.tables.columns.market" },
      { key: "paymentState", labelKey: "chinaAdmin.tables.columns.paymentState" },
      { key: "exceptionReason", labelKey: "chinaAdmin.tables.columns.exceptionReason" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "O-202605020339",
        cells: {
          id: cell("O-202605020339"),
          name: cell("超时未支付订单"),
          status: statusCell("chinaAdmin.status.order.cancelled", "grey"),
          market: cell("城北果蔬批发中心"),
          paymentState: cell("未支付"),
          exceptionReason: cell("支付超时自动关闭占位"),
          updatedAt: cell("2026-05-02 14:08"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
  exceptionOrders: {
    filters: ["异常类型", "风险等级", "所属市场", "负责人"],
    columns: [
      { key: "id", labelKey: "chinaAdmin.tables.columns.id" },
      { key: "name", labelKey: "chinaAdmin.tables.columns.name" },
      { key: "status", labelKey: "chinaAdmin.tables.columns.status" },
      { key: "market", labelKey: "chinaAdmin.tables.columns.market" },
      { key: "deliveryMode", labelKey: "chinaAdmin.tables.columns.deliveryMode" },
      { key: "exceptionReason", labelKey: "chinaAdmin.tables.columns.exceptionReason" },
      { key: "owner", labelKey: "chinaAdmin.tables.columns.owner" },
      { key: "updatedAt", labelKey: "chinaAdmin.tables.columns.updatedAt" },
      { key: "actions", labelKey: "chinaAdmin.tables.columns.actions" },
    ],
    rows: [
      {
        id: "O-202605020771",
        cells: {
          id: cell("O-202605020771"),
          name: cell("跨档口统一配送订单"),
          status: statusCell("chinaAdmin.status.order.refunding", "red"),
          market: cell("三门海鲜市场 / 城北果蔬批发中心"),
          deliveryMode: cell("跨档口统一配送"),
          exceptionReason: cell("配送异常引发售后，需人工核实"),
          owner: cell("统一配送调度组"),
          updatedAt: cell("2026-05-02 16:33"),
        },
        actions: ["view", "remark"],
      },
    ],
  },
}
